{{- if .Values.coreDNS.autoConfigure -}}
# Cleanup job to remove import statement and volume mount from CoreDNS
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "coredns-ingress-sync.fullname" . }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coredns-ingress-sync.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "coredns-ingress-sync.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "coredns-ingress-sync.serviceAccountName" . }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: cleanup
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/controller"]
        args: ["--mode=cleanup"]
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INGRESS_CLASS
          value: {{ .Values.controller.ingressClass | quote }}
        - name: TARGET_CNAME
          value: {{ .Values.controller.targetCname | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.controller.logLevel | quote }}
        - name: LEADER_ELECTION_ENABLED
          value: {{ .Values.leaderElection.enabled | quote }}
        - name: COREDNS_NAMESPACE
          value: {{ .Values.coreDNS.namespace | quote }}
        - name: DYNAMIC_CONFIGMAP_NAME
          value: {{ .Values.controller.dynamicConfigMap.name | quote }}
        - name: DYNAMIC_CONFIG_KEY
          value: {{ .Values.controller.dynamicConfigMap.key | quote }}
        - name: COREDNS_CONFIGMAP_NAME
          value: {{ .Values.coreDNS.configMapName | quote }}
        - name: COREDNS_AUTO_CONFIGURE
          value: {{ .Values.coreDNS.autoConfigure | quote }}
        {{- range $key, $value := .Values.controller.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
{{- end }}
