# Cleanup job to remove import statement and volume mount from CoreDNS
# Always runs on uninstall regardless of autoConfigure setting to handle upgrades/downgrades
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "coredns-ingress-sync.fullname" . }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coredns-ingress-sync.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "coredns-ingress-sync.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "coredns-ingress-sync.serviceAccountName" . }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: cleanup
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/controller"]
        args: ["--mode=cleanup"]
        env:
        # Only the minimal environment variables needed for cleanup
        - name: COREDNS_NAMESPACE
          value: {{ .Values.coreDNS.namespace | quote }}
        - name: DYNAMIC_CONFIGMAP_NAME
          value: {{ .Values.controller.dynamicConfigMap.name | quote }}
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
