{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coredns-ingress-sync.serviceAccountName" . }}
  labels:
    {{- include "coredns-ingress-sync.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if .Values.coreDNS.autoConfigure }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
  {{- else }}
  {{- if .Values.coreDNS.autoConfigure }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- end }}
  {{- end }}
{{- end }}
