# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    assignees:
      - "rl-io"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
      - "security"
    # Group minor and patch updates together to reduce PR noise
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Only allow security updates for major versions to avoid breaking changes
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker base image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    assignees:
      - "rl-io"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    assignees:
      - "rl-io"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
      - "security"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
