name: Release Helm Chart

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.12.0

    - name: Cache Helm repositories
      uses: actions/cache@v4
      with:
        path: ~/.cache/helm
        key: ${{ runner.os }}-helm-release-${{ hashFiles('**/Chart.yaml') }}
        restore-keys: |
          ${{ runner.os }}-helm-release-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Package and Push Helm Chart
      run: |
        # Package the chart
        helm package helm/coredns-ingress-sync

        # Push to GitHub Packages (OCI format)
        helm push coredns-ingress-sync-*.tgz oci://ghcr.io/rl-io/coredns-ingress-sync
