name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Trigger CI for release PR
        if: |
          steps.release.outputs.prs_created == 'true' && 
          steps.release.outputs.prs != '' && 
          steps.release.outputs.prs != 'null'
        env:
          PRS_OUTPUT: ${{ steps.release.outputs.prs }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release-please
          client-payload: |
            {
              "pr_number": "${{ fromJSON(env.PRS_OUTPUT)[0].number }}",
              "ref": "${{ fromJSON(env.PRS_OUTPUT)[0].headBranchName }}"
            }


